import PDFDocument from "pdfkit";
import { COMPANY_NAME, PLATFORM_NAME } from "@/config/constants";
import { formatCurrency, formatDate } from "@/lib/utils";
import type { Invoice } from "@/types";

export async function generateInvoicePdf(invoice: Invoice) {
  return new Promise<Buffer>((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 48 });
    const chunks: Buffer[] = [];
    doc.on("data", (chunk) => chunks.push(Buffer.from(chunk)));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.fillColor("#0F6E56").fontSize(22).text(PLATFORM_NAME);
    doc.fillColor("#5C6B66").fontSize(11).text(COMPANY_NAME);
    doc.moveDown();
    doc.fillColor("#12201C").fontSize(18).text("Invoice");
    doc.moveDown(0.5);
    doc.fontSize(11).fillColor("#12201C");
    doc.text(`Invoice number: ${invoice.invoiceNumber}`);
    doc.text(`Invoice date: ${formatDate(invoice.paymentDate)}`);
    doc.text(`Status: ${invoice.status.toUpperCase()}`);
    doc.moveDown();
    doc.text(`Billed to: ${invoice.customerName}`);
    doc.text(invoice.customerEmail);
    doc.moveDown();
    doc.text(`Plan: ${invoice.planName}`);
    doc.text(`Amount: ${formatCurrency(invoice.amount, invoice.currency)}`);
    if (invoice.taxAmount > 0) {
      doc.text(`${invoice.taxLabel || "Tax"}: ${formatCurrency(invoice.taxAmount, invoice.currency)}`);
    }
    if (invoice.paymentId) doc.text(`Payment ID: ${invoice.paymentId}`);
    if (invoice.subscriptionId) doc.text(`Subscription ID: ${invoice.subscriptionId}`);
    if (invoice.renewalDate) doc.text(`Next renewal: ${formatDate(invoice.renewalDate)}`);
    doc.moveDown(2);
    doc.fontSize(9).fillColor("#5C6B66").text(
      "This invoice was generated by Vivexa DeployX. Review with your finance/legal team before relying on it for formal tax purposes.",
    );
    doc.end();
  });
}
